### ISSUE TITLE
Can not install the lib: pyjwkest-1.4.2

### ISSUE THREAD

**Issue by ShuoShenDe** [nephila/python-taiga#189]
## Description
I wanna install the taiga in my python environment(3.10)，However,
 

## Steps to reproduce
pip install python_taiga-1.3.0-py2.py3-none-any.whl

or

pip install pip install python-taiga

## Versions

Python version: 3.10
Operating System: [Your OS (e.g., Ubuntu 20.04, macOS, etc.)]
Virtual Environment: Yes
python-taiga version: 1.3.0

## Actual behaviour
```

WARNING: Ignoring invalid distribution -ip (/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages)
Processing ./python_taiga-1.3.0-py2.py3-none-any.whl
Requirement already satisfied: requests>2.11 in /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages (from python-taiga==1.3.0) (2.28.1)
Requirement already satisfied: six>=1.9 in /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages (from python-taiga==1.3.0) (1.16.0)
Requirement already satisfied: python-dateutil>=2.4 in /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages (from python-taiga==1.3.0) (2.8.2)
Collecting pyjwkest>=1.0 (from python-taiga==1.3.0)
  Using cached pyjwkest-1.4.2.tar.gz (41 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running egg_info
      creating /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info
      writing /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/SOURCES.txt'
      [12/02/24 10:24:16] ERROR    listing git files failed - pretending     git.py:26
                                   there aren't any
      reading manifest file '/tmp/pip-pip-egg-info-7_xnykoc/pyjwkest.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kyqctiud/pyjwkest_2c675ed9fe644409acb1b09beecf9ea5/setup.py", line 29, in <module>
          setup(
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 313, in run
          self.find_sources()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in find_sources
          mm.run()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.prune_file_list()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/command/sdist.py", line 162, in prune_file_list
          super().prune_file_list()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 380, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 267, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/bd8090/Documents/airflow/airflow_env/lib/python3.10/site-packages/setuptools/_core_metadata.py", line 285, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

## Additional information

it sounds like pyjwkest has problem to install here

**Comment by protoroto** [comment]
@ShuoShenDe Hi! I'm not able to reproduce this. I've created a virtualenv with python 3.10.12, and installed python-taiga correctly. Could you please check which version of setuptools you have? I don't think that's related to python-taiga at all

**Comment by psybers** [comment]
This is a problem with `setuptools`, not this library.

See: https://github.com/pypa/setuptools/issues/4483

**Comment by Paras-Gith** [comment]
Hello Miss,
Thanks for pointing that out. You’re right — the issue isn’t with python‑taiga itself, but with setuptools. The pyjwkest dependency triggers a bug in older setuptools versions (see the @psybers comment) . Upgrading pip, setuptools, and wheel inside the virtual environment usually resolves it.
A similar thing happened to me when I was installing a different version of Airflow — the installation failed because my build tools were outdated, not because of Airflow itself. Once I upgraded setuptools, the issue was resolved. 
i know that the core problem is not similar.
