### ISSUE TITLE
No such file error for README.rst during setup

### ISSUE THREAD

**Issue by mfkaptan** [nephila/python-taiga#45]
running `python setup.py egg_info` gives 
```
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    long_description=read('README.rst'),
  File "setup.py", line 8, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
IOError: [Errno 2] No such file or directory: 'README.rst'
```

I think it should be `README.md` instead of `README.rst`

**Comment by yakky** [comment]
Fixed in #46
