### ISSUE TITLE
Stuck when trying to get a project object

### ISSUE THREAD

**Issue by foxmask** [nephila/python-taiga#49]
when I try to do this 
```
new_project = api.projects.get_by_slug(taiga.project_name)
```
I get
```
Starting new HTTPS connection (1): api.taiga.io
<taiga.client.TaigaAPI object at 0x7f4b3f9030f0>
SLUG????  Trigger-Happy endpoint  projects
Starting new HTTPS connection (1): api.taiga.io
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 420, in _handle_results
    task = get()
  File "/usr/lib/python3.4/multiprocessing/connection.py", line 251, in recv
    return ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'status_code'
```
I made a print inside of `get_by_slug` and could print the "slug" like we can see above, but once it tries 
```
        response = self.requester.get(
            '/{endpoint}/by_slug?slug={slug}',
            endpoint=self.instance.endpoint,
            slug=slug
        )
```
its over, i'm stuck

**Comment by yakky** [comment]
@foxmask could you post a complete traceback and the code you are using? I can't reproduce this
